# Name of loaded config, to show to user
name = "DEV9 no-shutdown driver"

# Modules to load
[[module]]
file = "dev9_ns.irx" # no-shutdown version, to prevent games shutting down the dev9
env = ["LE", "EE"]

# Faking strategy
# ---------------
# To allow games to use the hdd or network:
# - dev9 (no-shutdown) is resident, and can be used
[[fake]]
file = "DEV9.IRX"
name = "dev9"
version = 0x0208
startrv = 0 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
