IOP_CFLAGS += -mno-check-zero-division
#IOP_CFLAGS += -DNO_BDM
IOP_OBJS = main.o smap.o xfer.o ministack.o udpbd.o udptty.o imports.o exports.o


include $(PS2SDK)/Defs.make
include ../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
