IOP_CFLAGS += -mno-check-zero-division -I../smap/include
IOP_OBJS = main.o ministack_eth.o ministack_arp.o ministack_ip.o ministack_udp.o udptty.o udpbd.o imports.o
IOP_OBJS_DIR = obj/
IOP_BIN = udpbd.irx

include ../Rules.make
