IOP_OBJS = cdvdman.o ioops.o ncmd.o scmd.o searchfile.o streaming.o ioplib.o device-fhi.o smsutils.o imports.o exports.o
IOP_INCS = -I../common

include ../../Defs.make
include ../Rules.bin.make
include ../Rules.make
