name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2max/dev:v20250725-2
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make clean all release

      - name: Upload release as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            releases/*.7z

      - name: Create latest release
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            releases/*.7z
