name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          make clean all

      - name: Define target name
        id: slug
        run: |
          echo "TARGET=neutrino-$(date "+%Y%m%d")-${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Pack release
        run: |
          TARGET=${{ env.TARGET }}
          cd ee/loader
          make copy
          mkdir $TARGET
          cp *.elf $TARGET/
          cp -r modules/ $TARGET/modules/
          cp -r config/ $TARGET/config/
          cp ../../README.md $TARGET/
          7z a -t7z $TARGET.7z $TARGET/*

      - name: Upload release as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: |
            ee/loader/*.7z

      - name: Create latest release
        if: github.ref == 'refs/heads/master'
        uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            ee/loader/*.7z

  build-iopcore-debug:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          make clean all IOPCORE_DEBUG=1

      - name: Define target name
        id: slug
        run: |
          echo "TARGET=neutrino-IOPCORE_DEBUG-$(date "+%Y%m%d")-${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Pack release
        run: |
          TARGET=${{ env.TARGET }}
          cd ee/loader
          make copy
          mkdir $TARGET
          cp *.elf $TARGET/
          cp -r modules/ $TARGET/modules/
          cp -r config/ $TARGET/config/
          cp ../../README.md $TARGET/
          7z a -t7z $TARGET.7z $TARGET/*

      - name: Upload release as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: |
            ee/loader/*.7z

  build-eesio-debug:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          make clean all EESIO_DEBUG=1

      - name: Define target name
        id: slug
        run: |
          echo "TARGET=neutrino-EESIO_DEBUG-$(date "+%Y%m%d")-${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Pack release
        run: |
          TARGET=${{ env.TARGET }}
          cd ee/loader
          make copy
          mkdir $TARGET
          cp *.elf $TARGET/
          cp -r modules/ $TARGET/modules/
          cp -r config/ $TARGET/config/
          cp ../../README.md $TARGET/
          7z a -t7z $TARGET.7z $TARGET/*

      - name: Upload release as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: |
            ee/loader/*.7z

  build-debug:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          make clean all IOPCORE_DEBUG=1 EESIO_DEBUG=1

      - name: Define target name
        id: slug
        run: |
          echo "TARGET=neutrino-debug-$(date "+%Y%m%d")-${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Pack release
        run: |
          TARGET=${{ env.TARGET }}
          cd ee/loader
          make copy
          mkdir $TARGET
          cp *.elf $TARGET/
          cp -r modules/ $TARGET/modules/
          cp -r config/ $TARGET/config/
          cp ../../README.md $TARGET/
          7z a -t7z $TARGET.7z $TARGET/*

      - name: Upload release as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: |
            ee/loader/*.7z
